-- Tabel untuk data utama (baterai, device, IP)
CREATE TABLE battery_data (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    device_type TEXT,
    os_name TEXT,
    browser_name TEXT,
    battery_level TEXT,
    battery_charging TEXT,
    ip_address TEXT,
    location TEXT,
    timestamp TIMESTAMPTZ
);

-- Tabel untuk DNS logs
CREATE TABLE dns_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    source_ip TEXT,
    domain TEXT,
    timestamp TIMESTAMPTZ
);

-- Izinkan insert tanpa auth
CREATE POLICY "Enable insert for everyone" ON battery_data
    AS PERMISSIVE FOR INSERT TO public
    WITH CHECK (true);

CREATE POLICY "Enable insert for everyone" ON dns_logs
    AS PERMISSIVE FOR INSERT TO public
    WITH CHECK (true);

-- Izinkan read tanpa auth (untuk dashboard)
CREATE POLICY "Enable read for everyone" ON battery_data
    AS PERMISSIVE FOR SELECT TO public
    USING (true);

CREATE POLICY "Enable read for everyone" ON dns_logs
    AS PERMISSIVE FOR SELECT TO public
    USING (true);